# Generated by Django 2.2.5 on 2019-10-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_code', models.CharField(max_length=8)),
                ('movie_title', models.CharField(max_length=128)),
                ('laugh', models.PositiveSmallIntegerField()),
                ('sad', models.PositiveSmallIntegerField()),
                ('depress', models.PositiveSmallIntegerField()),
                ('fear', models.PositiveSmallIntegerField()),
                ('lightness', models.PositiveSmallIntegerField()),
                ('heaviness', models.PositiveSmallIntegerField()),
                ('gratifying', models.PositiveSmallIntegerField()),
                ('immersion', models.PositiveSmallIntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movieemotion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
