# Generated by Django 2.2.5 on 2019-10-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviescore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviescore',
            name='owner',
        ),
    ]
