# Generated by Django 2.2.5 on 2019-10-11 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviescore', '0002_remove_moviescore_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviescore',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviescore', to=settings.AUTH_USER_MODEL),
        ),
    ]
