export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";

export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_LOADED = "USER_PROFILE_LOADED";

//
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

//Moviescore

export const GET_SCORE = "GET_SCORE";
export const GET_MOVIE_INFO = "GET_MOVIE_INFO";
export const CLEAR_MOVIE_INFO = "CLEAR_MOVIE_INFO";
export const GET_RECENT_MOVIE_INFO = "GET_RECENT_MOVIE_INFO";

export const GET_USER_EMOTION_SCORE = "GET_USER_EMOTION_SCORE";
export const COLLABO_TO_DETAIL = "COLLABO_TO_DETAIL";
