# Generated by Django 2.2.5 on 2019-10-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191022_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watchedMovie',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
