# Generated by Django 2.2.5 on 2019-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movieCd', models.CharField(max_length=8)),
                ('movieNm', models.CharField(max_length=128)),
                ('movieNmEn', models.CharField(max_length=128)),
                ('prdtYear', models.PositiveSmallIntegerField()),
                ('openDt', models.PositiveSmallIntegerField()),
                ('prdtStatNm', models.CharField(max_length=128)),
                ('repGenre', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('repNation', models.CharField(max_length=128)),
                ('nations', models.CharField(max_length=128)),
                ('typeNm', models.CharField(max_length=128)),
                ('showTm', models.PositiveSmallIntegerField()),
                ('directors', models.CharField(max_length=128)),
                ('actors', models.TextField()),
                ('actors_en', models.TextField()),
                ('cast', models.TextField()),
                ('cast_en', models.TextField()),
                ('companyCd', models.TextField()),
                ('companyNm', models.TextField()),
                ('companyNmEn', models.TextField()),
                ('companyPartNm', models.TextField()),
                ('watchGradeNm', models.TextField()),
            ],
        ),
    ]
