# Generated by Django 2.2.5 on 2019-10-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='posterUrl',
            field=models.TextField(blank=True),
        ),
    ]
