# Generated by Django 2.2.5 on 2019-10-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieInfo', '0002_movieinfo_posterurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='posterUrl',
            new_name='poster',
        ),
    ]
