# Generated by Django 2.2.5 on 2019-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movieCd', models.CharField(max_length=8)),
                ('movieNm', models.CharField(max_length=128)),
                ('impression', models.PositiveSmallIntegerField(default=0)),
                ('fear', models.PositiveSmallIntegerField(default=0)),
                ('anger', models.PositiveSmallIntegerField(default=0)),
                ('sadness', models.PositiveSmallIntegerField(default=0)),
                ('fun', models.PositiveSmallIntegerField(default=0)),
                ('boredom', models.PositiveSmallIntegerField(default=0)),
                ('positive', models.PositiveSmallIntegerField(default=0)),
                ('negative', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
