# Generated by Django 2.2.5 on 2019-10-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviescore', '0003_moviescore_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviescore',
            name='owner',
        ),
    ]
